version: "3.8"
services:
  #################################################################################
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672
  #################################################################################
  stock-service:
    image: deliverymuch/backend-challenge:stock-service
    networks:
      - app-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure
  #################################################################################
  mongo:
    container_name: mongo-container
    image: mongo
    networks:
      - app-network
    volumes:
      - ./db-data:/data/db
    ports:
      - "27017:27017"
    restart: on-failure
  #################################################################################
  api:
    build: .
    image: backend-challenge-api
    container_name: backend-delivery_api
    networks:
      - app-network
    ports:
      - 3010:3010
    depends_on:
      - mongo
    links:
      - mongo
      - rabbitmq
    restart: on-failure
networks:
  app-network:
    driver: bridge
